In [91]:
import pandas as pd

In [92]:
df = pd.read_csv('data.csv')

In [93]:
df.head()

,area_sqft,bedrooms,bathrooms,floors,age_years,distance_city_km,parking_spaces,price
0,3774,6,5,3,24,7.14,3,775146
1,1460,3,3,3,22,9.75,3,261114
2,1894,2,2,2,1,21.25,2,367626
3,1730,4,5,1,8,5.68,1,382686
4,1695,2,2,1,13,20.84,0,279810

In [94]:
df.isna().sum()

area_sqft           0
bedrooms            0
bathrooms           0
floors              0
age_years           0
distance_city_km    0
parking_spaces      0
price               0
dtype: int64

In [95]:
x = df.drop('price', axis=1)
y = df['price']

In [96]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [97]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [98]:
from sklearn.metrics import r2_score
y_pred = model.predict(x_test)
r2_score(y_test, y_pred)

0.9894387723080019

In [99]:
import joblib
joblib.dump(model, 'model.pkl')

['model.pkl']